os: linux
dist: focal
vm:
  size: large
language: generic
addons:
  apt:
    packages:
      - libxml-xpath-perl
services:
  - docker

env:
  global:
    - DOCKER_ORG=zencash
    - IMAGE_NAME=sc-ci-base
    - PROD_RELEASE_BRANCH=master
    - PUBLISH_BUILD=false

script:
  - source ci/setup_env.sh
  - ci/travis_keep_alive.sh
  - ci/script.sh tests

jobs:
  include:
    - name: rust_1.51_asm_target-feature_cargo_test
      env: IMAGE_TAG='bionic_rust-1.51.0_jdk-11_latest' RUSTFLAGS='-C target-feature=+bmi2,+adx --emit=asm' TESTS='000,002'
#    - name: rust_1.51_asm_target-feature_mvn_test
#      env: IMAGE_TAG='bionic_rust-1.51.0_jdk-11_latest' RUSTFLAGS='-C target-feature=+bmi2,+adx --emit=asm' TESTS='001,003'
    - name: rust_1.51_asm_target-feature_mvn_release
      if: tag IS present
      env: PUBLISH_BUILD=true IMAGE_TAG='bionic_rust-1.51.0_jdk-11_latest' RUSTFLAGS='-C target-feature=+bmi2,+adx --emit=asm' TESTS='000,001,002,003'

deploy:
  provider: script
  script: ci/script.sh release
  skip_cleanup: true
  on:
    tags: true
    condition: $PUBLISH_BUILD = true